### ISSUE TITLE
Hours are bullshit, but what about salary?

### ISSUE THREAD

**Issue by ghost** [holman/feedback#150]
I recently came across this article http://zachholman.com/posts/how-github-works/, and I really enjoyed reading it. However, there's one thing I was wondering after reading this article: you said that you don't value hours, but quality. But how is that done with salary? What do you base that on?

**Comment by cirosantilli** [comment]
120 - 160 according to glassdoor: http://www.glassdoor.com/Salary/GitHub-Salaries-E671945.htm

**Comment by Haglerd** [comment]
Is that accurate?
