### ISSUE TITLE
Automation of pull request forwarding via mail?

### ISSUE THREAD

**Issue by dscho** [holman/feedback#151]
Hi Zach,

since you asked so nicely: we have the scenario where some of the core team (msysGit) want to review pull requests on our mailing list (actually, a Google Group). Is there an easy way to forward pull requests of that project, and only pull requests, via mail to that list?

I can think of a couple of hacky ways, none of them really satisfying. Or robust.

Thanks,
Dscho

**Comment by zhouyoufu** [comment]
All
