### ISSUE TITLE
Reporting spam github users

### ISSUE THREAD

**Issue by sdball** [holman/feedback#164]
Is there an official way to report github users that are clearly just spam accounts?

e.g. https://github.com/StevenGerrard

**Comment by echnique** [comment]
hey guys, just so you know... i'm straight.

**Comment by Andersos** [comment]
@wadewilliams How do you figure out the grade of a page in page rank?

**Comment by wadewilliams** [comment]
http://lmgtfy.com/?q=github+report+spam&l=1
