### ISSUE TITLE
Option to delete branch after merging pull request?

### ISSUE THREAD

**Issue by jefftougas** [holman/feedback#204]
Any chance we could get a checkbox in the pull request merge dialog (defaulted to unchecked) that when checked will cause the branch in question to be deleted from the repository?

I find that my repositories frequently get cluttered up with dozens of branches that are merged into master and hence no longer necessary. After this reaches a certain number I typically go through and delete all the old branches by hand, and send a politely forceful email to my coworkers asking them to remember to clean up after themselves.

**Comment by guilpejon** [comment]
I think this should be reopened. I really miss a checkbox to mark the deletion of the branch after the merge.

**Comment by holman** [comment]
You should probably talk to GitHub about it then.

**Comment by guilpejon** [comment]
Guess I should start reading before commenting lol
