### ISSUE TITLE
Your hardware @ work and for private use?

### ISSUE THREAD

**Issue by huNt-FMJ** [holman/feedback#252]
Hey Holman,

 I was wondering what kind of hardware you yourself are using @ work and for private use (maybe something different).
I've seen you use mac stuff, but which one exactly and which you like the most? :)

Thx in advance.

Cheers 
Michael

**Comment by hahmed** [comment]
@holman just wondering what your setup is now? Still using a 15inch MacBook Pro Retina? did you make sure to go for the 16G ram or is 8 good for your dev? Thanks.

**Comment by holman** [comment]
Yup. Might switch to the new MacBook in a year or two once it's fast enough.

RAM's so cheap now that 16GB makes a lot of sense to me. I haven't had to worry about RAM in years because of that.
