### ISSUE TITLE
Linking to lines within a Markdown text file?

### ISSUE THREAD

**Issue by IanVaughan** [holman/feedback#305]
I often link to source code via the #L param in the URI.

e.g. : https://github.com/github/learn.github.com/blob/gh-pages/episodes.yaml#L1

But is there a way to link to lines within a Markdown file?

e.g. https://github.com/github/learn.github.com/blob/gh-pages/README.markdown#L1 (does not work!)

I know I can link to 'sections', but lines are much better!

e.g. https://github.com/github/learn.github.com/blob/gh-pages/README.markdown#learngithubcom

**Comment by davepacheco** [comment]
+1

**Comment by pfmooney** [comment]
+1

**Comment by tjfontaine** [comment]
wait there's this *and* https://github.com/isaacs/github?

+1 even though +1 trolls me to another level thanks GitHub.

**Comment by holman** [comment]
This is not an avenue for GitHub support. If you want to shoot us a note to support@github.com, we can continue the conversation there, though!
