### ISSUE TITLE
Code obfuscation

### ISSUE THREAD

**Issue by justincase** [holman/feedback#345]
In [Introducing GitHub Enterprise](https://news.ycombinator.com/item?id=3183323) you mentioned that "GitHub Enterprise uses code obfuscation with MRI". Can you share any details on which tool is used for the obfuscation?

**Comment by tbardzil** [comment]
The page below says that Github has moved away from RubyEncoder and is now using something custom. Can you share any more details?

https://news.ycombinator.com/item?id=9930838

**Comment by holman** [comment]
Nope

**Comment by josephholsten** [comment]
Could you sell us details? ;-)

**Comment by holman** [comment]
No idea what they do anymore.

**Comment by hakusaro** [comment]
@josephholsten there are details on this bug bounty blog post: http://blog.orange.tw/2017/01/bug-bounty-github-enterprise-sql-injection.html
