### ISSUE TITLE
Continuous Deployment at Github

### ISSUE THREAD

**Issue by rgirardRev** [holman/feedback#405]
I had questions regarding the QA/Staging portion of your deployment workflow. From what I have gathered through some research, it looks like development goes right to production. QA/Staging takes place in between there I assume at some point. How does that work. Do you just deploy one feature branch at a time to test in the QA env? Do you have lots of QA servers available to test on?

Any additional information on this would be great, as I am trying to implement similar procedures and want to make sure I understand the whole process.

Thanks!

**Comment by akondrahman** [comment]
Great discussion ... I would like to know more ... 

1. What types of testing does Github perform ? Does Github do unit testing, functional testing, integration testing, or A/B testing ? 

2. What about dark launches ? 

3. Does Github use any packaging tool to deploy the Github changes ?

**Comment by holman** [comment]
> What types of testing does Github perform ?

Unit/functional/integration.

> What about dark launches ?

Yup, tons. I go into some more detail in [Move Fast and Break Nothing](http://zachholman.com/talk/move-fast-break-nothing/).

> Does Github use any packaging tool to deploy the Github changes ?

[Heaven](https://github.com/holman/feedback/issues?q=is%3Aissue+heaven).

**Comment by akondrahman** [comment]
Thanks a bunch !!

**Comment by Andersos** [comment]
> but the machine themselves are limited to staff only. 
Is this limitation by user account and is staff always sent to staff production machines?

**Comment by holman** [comment]
You can toggle in and out of it as you see fit.

**Comment by intel352** [comment]
@holman You note that deploys only occur once tests are all green. What about new features that sneak in without an accompanying test? Is there any process to ensure complete code coverage?

If you could expound upon your testing rigors, that would be appreciated (or a link to where this may have already been discussed).

I've been spearheading an effort within my own team to get functional tests in place (via CasperJS, ensure critical path functions for customers on an ecommerce platform), and once we have solid coverage there, I'll start getting unit/integration tests in place, so hearing the Github approach is helpful.

**Comment by holman** [comment]
> Is there any process to ensure complete code coverage?

No.

**Comment by atomical** [comment]
Do you have staging DB servers that are wiped out before each new deploy? How do you handle migrations that may need to be changed or rewritten after they are deployed to a staging server?
