### ISSUE TITLE
Summer internships for 2014?

### ISSUE THREAD

**Issue by ethnt** [holman/feedback#431]
I know GitHub hasn't had interns in the past, but are internships a possibility for this coming summer? GitHub seems like an awesome place to work!

Thanks! :smile:

**Comment by bhargavrpatel** [comment]
psst... any updates?

**Comment by holman** [comment]
You'd have to ask GitHub.

**Comment by nicolasmccurdy** [comment]
They have some listed for 2016 now: https://github.com/about/jobs#internships

**Comment by TarangKhanna** [comment]
Thanks!^

**Comment by rajeevpunna** [comment]
waiting for that  moment
