### ISSUE TITLE
How does Github hire?

### ISSUE THREAD

**Issue by danielvu14** [holman/feedback#434]
Hey Zach,

My name is Daniel, I'm the kid that was tweeting you about the Technical Supportocat position and asking questions and the whatnot on Twitter. But I felt I should explain myself because on Twitter it cannot be done easily.

So I'm a 20 year old college dropout, looking for work, and had previously used Github in a poor attempt to code (I'm new to coding and wish my high school and college was not so into standardized testing hence why I stopped school). My writing is awesome as many people say, but I have done a poor job of updating my blog (haven't done it since June). Ruby is something I'm learning as of right now, but geez, looking at the core values and ideals of Github, made me want to join the team so bad, I'm not even kidding. It's not the benefits, but when I read about Github, it was a dream come true for me. Really want to help people out, code, and have a blast in doing so.

But what got me wondering after submitting my application was how does Github select  candidates for the job? Do they have the traditional interview process, looking at GPA/SAT/what courses you took etc. or is it a completely different manner such as looking at projects and portfolios like Google is starting to do?

Hope that explains a bit about myself in addition to having the question of how does Github hire.

**Comment by Kunal0795** [comment]
Hello, I , a clg passout came across this post just now while browsing. I hope you are doing well Sir Daniel . I had the same question in my mind but I am 12 years late ig . Thank you Sir holman for your insights as well .
