### ISSUE TITLE
@mentioning other teams that you're not a part of

### ISSUE THREAD

**Issue by wadewilliams** [holman/feedback#469]
I'm not sure if this was always the way organizations and comments have worked but with the recent (awesome) updates: 

 We have teams for legal, designers, and developers in our organization. It seems as if someone who is on the developers team cannot @mention the designers or legal teams. Is this intended? As an organization owner, you can @mention any team.

**Comment by teoruiz** [comment]
:+1: for this actually coming.

**Comment by timotheeg** [comment]
:+1:

**Comment by zehua** [comment]
:+1:

**Comment by rprieto** [comment]
Great to hear this is in progress, since adding an entire organisation to "Owners" isn't really practical :+1:  
Any update on a potential ETA?

(as an alternative, we wouldn't mind adding everyone to "Owners" if it didn't include billing & org admin rights... maybe another group?)

**Comment by holman** [comment]
You'd have to ask GitHub.

**Comment by joshhiggins22** [comment]
:+1:
