### ISSUE TITLE
Best practice for feature requests on Github projects

### ISSUE THREAD

**Issue by dheerosaur** [holman/feedback#47]
I understand that you would prefer a pull request. But, I use many projects which are made in languages I have never used. For example, I have a feature request on your boom project.

**Comment by marchy** [comment]
Opening an issue can have a negative connotation that something is "wrong" with the project. A feature request is an idea and not representative of that. GitHub really SHOULD have a separate feature request portion (or at least an issue type called Feature Request). Bug lists / issues is definitely not the place for them.

**Comment by dzidzitop** [comment]
This world is cruel. Someone telling about something "wrong" is for good, baby.

**Comment by dooctavian** [comment]
I was here looking for the same thing.  But its because I applied a negative connotation to the word Issue which is undeserving.
Most of us associate an issue with a problem.
But an issue could also mean a regular installment, publication.  A progression

**Comment by nfisher** [comment]
I have an issue, your product doesn't fulfil X. Seems to fit then simply label with "feature".

**Comment by Michaelsy** [comment]
When I have an idea, I let the issue-title begin with [Feature Request]. The psychological aspect should not be underestimated.

**Comment by Michaelsy** [comment]
> Someone should submit an issue to Github. To request this feature.

[Here](https://github.com/isaacs/github) is at least an inofficial place for issues and feature requests that you have for github.

**Comment by Kilozen** [comment]
Google is still sending people to this page for GitHub Feature Requests, so I'm just going to post **a more recent link to their current policy:** 
- https://github.com/community/community#making-suggestions 

(tldr; as of 2022 it's still not easy to submit feature requests to the GitHub devs.  You basically submit a 'discussion' topic and hope it gets enough attention.)

**Comment by FitzRoyX** [comment]
> Opening an issue can have a negative connotation that something is "wrong" with the project. A feature request is an idea and not representative of that. GitHub really SHOULD have a separate feature request portion (or at least an issue type called Feature Request). Bug lists / issues is definitely not the place for them.

Exactly. But also, suggestions and people wanting things is an infinite, constant stream that vastly outnumbers actual bugs. It inflates the base "issue" number and forces you into extraneous clicks to "filter" out non-issues. Renaming "Pull Request" to "PR" would free up space for a new tab. This is long overdue.
