### ISSUE TITLE
Custom Hoodies?

### ISSUE THREAD

**Issue by ckdarby** [holman/feedback#471]
I wish the github shop partnered with someone like http://spreadshirt.com for their API and allowed the option to get the github hoodie but with my own handle on it.

Just think how cool it'd be for you to own a github hoodie that had "@holman" on it!

**Comment by arnellebalane** [comment]
It's already more than a year since this issue was closed, is this still "staff-only"? It's really cool and I really want one :)

**Comment by holman** [comment]
Think so.

**Comment by ckdarby** [comment]
@arnellebalane This is the closest thing you'll find from Github directly http://github.myshopify.com/products/github-username-shirt
