### ISSUE TITLE
Office furniture

### ISSUE THREAD

**Issue by justincase** [holman/feedback#525]
Hi Zach,

Do you know where these desks come from? They look quite comfortable to work at with those Aeron work stools. 

![](http://static3.businessinsider.com/image/5037d69fecad045537000008-1200/plenty-of-room-for-dogs-to-hang-out-in-the-work-area-with-their-favorite-developers.jpg)

I'm also curious what brand the VESA mount on the left is:

![](http://static3.businessinsider.com/image/5037d6a2ecad044939000002-1200/github-has-its-share-of-women-developers-like-julie-horvath.jpg)

Cheers. Love the office snaps.

**Comment by agh** [comment]
@justincase As best I can remember that's an Ergotron WorkFit, the VESA mount you asked about.
