### ISSUE TITLE
Does .mailmap work for github?

### ISSUE THREAD

**Issue by skirpichev** [holman/feedback#551]
For example: [the repo with .mailmap](https://github.com/sympy/sympy) and [here the list of contributors](https://github.com/sympy/sympy/graphs/contributors).  It seems, some commits attributed to unknown person:
https://github.com/sympy/sympy/commits?author=wmark

git-check-mailmap works for me, e.g.:

```
$ git check-mailmap 'David Roberts (dvdr18 [at] gmail [dot] com) <devnull@localhost>'
David Roberts <dvdr18@gmail.com>
```

**Comment by SylvainCorlay** [comment]
@holman When a user changes his affiliation, he cannot verify his old email address to their account because if cannot be verified. Since GitHub does not use mailmap, how can we credit contributors for their commits without changing the commit history?

**Comment by holman** [comment]
`¯\_(ツ)_/¯`
