### ISSUE TITLE
Is GitHub still hosted on Rackspace?

### ISSUE THREAD

**Issue by ghost** [holman/feedback#553]
There use to be a Rackspace logo in the footer too.

![screen shot 2014-06-21 at 10 18 21 pm](https://cloud.githubusercontent.com/assets/141213/3348749/28b7fa8a-f93e-11e3-8056-9954db35e816.png)

**Comment by prameswar1** [comment]
Is still github.com hosted on [Carpathia](http://www.carpathia.com/). or they are using some public cloud provider AWS, Azure etc. for backup or storage.

**Comment by holman** [comment]
Think they're mostly on Carpathia, with a bunch of AWS augmentation too (though who knows, prolly should ask a Hubber).

**Comment by sharat** [comment]
I remember reading this some time back and referring this recently on [Kubernetes at GitHub](https://githubengineering.com/kubernetes-at-github/). GitHub call it [Metal cloud](https://githubengineering.com/githubs-metal-cloud/), their own cloud. It's certainly hard to live without Amazon services to anyone operates in the global scale.

**Comment by whatevergeek** [comment]
Where is it hostes now?
Any plans on eventually be hosted on Azure?

**Comment by holman** [comment]
They have something like four datacenters around the world at this point. Dunno specifics, though.
