### ISSUE TITLE
"Year of contributions" seems to be incorrect?

### ISSUE THREAD

**Issue by pronvit** [holman/feedback#555]
Not really a big issue, so not contacting support

![screen shot 2014-06-25 at 11 38 31 am](https://cloud.githubusercontent.com/assets/7973649/3379911/e6676bde-fbf9-11e3-8622-e072999fb4d0.png)

**Comment by igor-stoppa** [comment]
It's not a big deal, but I also find it misleading.
** Disclaimer ** I am not a native English speaker, but I would find it easier to understand if the label was something like: "Contributions during the last year" or "Contributions during period".
