### ISSUE TITLE
Keeping a Journal

### ISSUE THREAD

**Issue by shashankmehta** [holman/feedback#565]
In reference to: http://zachholman.com/posts/keeping-a-journal/

You mentioned that you use DayOne. Haven't you ever had the feeling of paranoia that someday DayOne might have a security incident and all your journal entries might become public? Sure, a lot of entries would be of the sort that you wouldn't care much about if they became public knowledge but I don't think anyone would be comfortable with a totally open book about them that's been written by them. If the journal doesn't have entries on your private moments, is it really a good enough journal then?

Would you prefer a self hosted version?

**Comment by srid** [comment]
Day One supports iCloud and Dropbox syncing. Though it is not entirely clear if they send data to Day One's middleman servers first.
