### ISSUE TITLE
Summer 2015 Internships

### ISSUE THREAD

**Issue by tejasmanohar** [holman/feedback#629]
Are internships a possibility for summer '15? GitHub sounds like a _sick_ place to work!

Thanks! :smile:

**Comment by tejasmanohar** [comment]
When do you estimate GitHub will know by? I'm *super interested* and would drop almost any other offer to work with the theme there... just want to make sure I don't accept another before it's announced.

[resume](http://goo.gl/pcREmW)

**Comment by holman** [comment]
No idea; nothing concrete at the moment.

**Comment by tejasmanohar** [comment]
Is there someone that you'd recommend reaching out to at the company?

**Comment by holman** [comment]
Can always shoot a note to support@github.com.
