### ISSUE TITLE
Markdown diff fails if the old file is empty

### ISSUE THREAD

**Issue by rossant** [holman/feedback#632]
I get [an error message](https://help.github.com/articles/rendering-differences-in-prose-documents/#viewing-complex-diffs) when I try to display a diff of a `.md` file in a PR, as soon as the old file exists but is empty. The problem doesn't only occur on complex files, but also on very small `.md` files. I worked around the problem by deleting the empty file and rebasing. Then the diff worked.

**Comment by holman** [comment]
Feel free to shoot a message to support@github.com.

**Comment by rossant** [comment]
Sure, done.
