### ISSUE TITLE
3rd Party App Permissions - Read and Write Public and Private Repos?

### ISSUE THREAD

**Issue by atheiman** [holman/feedback#635]
I recently found an excellent tool for converting GH issues to a KanBan Board: https://www.zenhub.io/

Unfortunately, I will not be able to use this application because it requires repository read and write access to all repos I contribute to. Although zenhub user agreement states that it will not save any data, I cannot authorize this app to read (or write to) my private repos due to legal restrictions at work.

1.  Why dont you buy zenhub and integrate it into GH core? It is an excellent application and it already shows its features natively in GH.

1.  Why is there no auth permission to read and write public repos separately from private repos? Or why is there no auth permission for only issues? Many GH users need an agile board for their issues, this seems like a common use-case to want access to repo issues and only issues.

There is an issue on ZenHub's support Issues board directly related to this issue: https://github.com/ZenHubIO/support/issues/77, and Im sure the issue exists for other's trying to find an app to manage an agile board but running into this permission problem.

Below is the information GH provides on third party application auth. It clearly states that GH is aware that this auth permission is a bit too expansive, so are you working to divide the scope of it currently?

https://help.github.com/articles/connecting-with-third-party-applications/

> Repositories
> Repository information includes the names of contributors, the branches you've created, and the actual files within your repository. Applications can request access for either public or private repositories on a user-wide level. **This is one of the most expansive configurations you can permit, so accept it with caution!**

**Comment by holman** [comment]
These are good point. Can't get into any details about things, but definitely good points. :+1:

**Comment by breck7** [comment]
> Why is there no auth permission to read and write public repos separately from private repos?
+1

I'd like to use some 3rd party apps with only my public repos. It would be nice if GitHub made it mandatory that apps support users who only provide access to public repos.

**Comment by Andersos** [comment]
Holman no longer works for GitHub. You should probably contact Github support
