### ISSUE TITLE
User keeps spamming repository because he doesn't want to receive notifications

### ISSUE THREAD

**Issue by Yonezpt** [holman/feedback#636]
The user @Yung1683 has been spamming the repository https://github.com/YePpHa/YouTubeCenter/issues for the past couple of days telling others that he does not want to receive more email notifications, he doesn't know that his current Watch option is responsible for that. We have tried to help him multiple times, but it is clear that he simply auto-replies in his email without reading the content whenever he receives a notification.

The following is a screenshot showing his entire activity since he created his account:

![ss](https://cloud.githubusercontent.com/assets/8498057/5755153/8d4b27d8-9c90-11e4-869b-8c7b4896efd2.png)

I already reported this user twice, but nothing happened.

I urge you (Github) to create a proper tool that will help us prevent these issues from happening again, give us a ban function so that whenever these things happen we aren't forced to wait for an action to be taken by Github, we aren't forced to chase after unofficial channels such as this repository to fetch faster help, nor be forced to go day and night after his spam comments constantly, deleting one by one while he bothers and angers everyone participating in the issues as well as the people watching the repository.

**Comment by Andersos** [comment]
Try contacting [Github support](https://github.com/contact)

**Comment by Yonezpt** [comment]
But that's exactly what the report button does, which is what I have done twice already.

**Comment by holman** [comment]
The report button's your best option; you can also ping support directly. Alternatively, you can block the user directly as well.
