### ISSUE TITLE
How does pagination work in GitHub API?

### ISSUE THREAD

**Issue by szimek** [holman/feedback#637]
Hey,

do you always count all records to calculate the last page in requests that return pagination headers or is it somehow optimized? We've got a project that uses PostgreSQL and with ~10 millions records in a table calculating the total count and the last page number with some additional conditions is really slow, so we don't return last page number anymore. Fortunately for us, we use infinite scrolling almost everywhere, so we can easily get away without it, but I was wondering how it works in GitHub, where you surely have much, much more data.

**Comment by holman** [comment]
It depends on the query, really. For some pages we don't calculate the total result set count- you typically see a `next/previous` link on the bottom. A lot of these pages are pulled from Git, which is a lot more expensive to pull total page count than from the database (usually- we've been optimizing this calculation a lot the last year or so, too).

For others, we're forced to calculate the total page size. Sometimes it's not that huge of a deal, sometimes it is. There are some tricks that can be done to force indexes, use counter caches, and so on. Just depends on the context.

**Comment by 102457** [comment]
slt
cv
