### ISSUE TITLE
RFC 92093π42.10: Things for @holman to write about 

### ISSUE THREAD

**Issue by holman** [holman/feedback#639]
I'm going to do the ever-elusive, much-discussed, never-seen ***REVERSE FEEDBACK REPO ISSUE CREATION DINGER*** by asking a question from all of *you*: is there anything you're interested in hearing about from me in blog form?

I just finished up writing a couple blog posts that I think I'll polish and publish next week, and since I'm currently in the middle of taking a few months off from GitHub, now's kind of a lovely time to cozy up next to my text editor and do a lot more writing. I'm also going to be doing at least one new major talk in March/April as I head to Australia and New Zealand, and there's definitely going to be a major written companion piece to that one since I loved doing the [*Move Fast and Break Nothing*](http://zachholman.com/talk/move-fast-break-nothing/) text writeup last time so much, so this might be good fodder for that, too.

I have a few pieces in mind already, and a couple other old drafts lying around, but if you have a burning desire to see me write something up, let me know and I'll definitely think on it. I might dig through some of the old issues in this repo and see if there's anything that makes sense to clean up as well. Also I want to probably get really drunk and write something like [Only 90s Web Developers Remember This](http://zachholman.com/posts/only-90s-developers/) sometime too, although it's hard to force excellence and/or incompetency. (Hidden bonus for all of you: that's me on the left with my grandfather, father, and brother in the nineties in the top photo of that post.)

Sound off in the comments, or file another issue on this repo if there's something specific and non-bloggy you're interested in, or ping me via email (zach at zachholman) if you'd rather be mad secret about that ish.

Happy 2015 y'all.

**Comment by karan** [comment]
How you spend your weekends.

**Comment by holman** [comment]
Hah, my weekends basically consist of me sitting on my couch for basically the entirety of it, so possibly not the most interesting of blog posts. ;) Weekends are real chill in my world.

**Comment by karan** [comment]
Ok. Your best tips for becoming as cool as you are. :smiley:

**Comment by jlfwong** [comment]
Would love to know how GitHub measures and optimizes web performance (particularly clientside to minimize time from server response to fully interactive JS + CSS).

**Comment by holman** [comment]
That could be an interesting post. Lots to talk about there.

Some interesting prior art from GitHubbers that you might be interested in in the meantime:

- Rohan's CSS performance talk: https://vimeo.com/54990931
- Rachel and Emily's talk on frontend and js construction and performance: https://www.youtube.com/watch?v=3mXH95lA-FQ

**Comment by boris** [comment]
How do you manage db migrations (i.e: `rake db:migrate`) at Github?

**Comment by hrishikeshs** [comment]
What career advice do you have for someone who is a young and talented programmer at a start-up if the programmer intends to become an tech entrepreneur one day?

**Comment by ttaylorr** [comment]
How do you deal with a lack of inspiration/motivation? Seems like it's a good topic to discuss, given your post "Inertia".

**Comment by vortec** [comment]
Please write a technical post about what it took to bring Git up to scale, how you made it fast and what mistakes you made.

**Comment by holman** [comment]
> Please write a technical post about what it took to bring Git up to scale, how you made it fast and what mistakes you made.

You might be interested in [this](http://zachholman.com/talk/how-to-build-a-github/) and [this](http://devslovebacon.com/conferences/bacon-2013/talks/my-mom-told-me-that-git-doesnt-scale).

**Comment by bradgessler** [comment]
How does Github scale its git archive store? NFS? ceph?

**Comment by sorenmat** [comment]
How you are doing onboarding of new employees, and how you keep them

**Comment by kevincupp** [comment]
Would love to hear your thoughts on remote working. Does GitHub have remote developers? If so, how do you work with them? Or, do you find the "water cooler moments" to be too crucial to give up, or that organic idea/solution generation can't happen as easily and quickly?

**Comment by szanto90balazs** [comment]
I'd like to hear about what's your opinion about native apps versus html+js apps. Github.com looks good on mobile, however I feel it might be even smoother and slicker if it was implemented using native technologies (iOS, Android, C+ ...).

**Comment by paulrose** [comment]
@holman Two posts in two days! Are you doing the Your Turn Challenge?

**Comment by holman** [comment]
Nope; just enjoying writing for a bit again. :)

**Comment by sburns** [comment]
What factors went into taking time off from GitHub?

**Comment by holman** [comment]
Had a decent week last week with five new posts: http://zachholman.com

Think I'm going to close this out for now; hope to continue writing regularly... that was fun! In the meantime, feel free to file an issue on this repo if you have any other specific questions about things. :metal:

**Comment by paulrose** [comment]
Good posts dude, a good read!
