### ISSUE TITLE
Controlling devices connected to raspberry pi remotely using an android app

### ISSUE THREAD

**Issue by dazilli** [holman/feedback#640]
Hi, I am building a home automation project for my Final Masters project. I have the hardware components working using python and nodejs. The remaining part is to control these components remotely from my android using an android application that I want to develop. But the thing is that I don't know how to start.
I have done some research on this and seen people do it, but they did not describe how they got it working.
Now my question is:
1. Do I have to install any thing into my raspberry pi for it to recognize my my application's commands?
2. What are the APIs I need to import into the java code on the android development part for this to be possible?
3. What line of Code do I need to write for this communication to occur?

Please I will really appreciate any help . Thanks.

**Comment by holman** [comment]
No idea! Haven't done that sort of thing before.
