### ISSUE TITLE
Promoting my things

### ISSUE THREAD

**Issue by davezych** [holman/feedback#641]
Let's say, hypothetically, I have an open source project I think people would find useful and want it to "get found" (I don't have one, but that's why this is hypothetical. This could also apply to blog posts, I guess). Since I'm not a very popular person, i.e. I don't have many twitter followers and I don't have a popular blog and whatnot, what do you think the best way to promote this stuff would be? Obviously the most important thing is a quality project, but if I have that, where do I post it?

**Comment by holman** [comment]
I wrote about this a little bit in 2011: http://zachholman.com/posts/open-source-marketing/

It's not exactly an attractive option, but I think a lot of grinding is acceptable before a popular becomes "popular". i.e., it takes a lot of blog posts or talks or tweets or similar things with not a ton of response for awhile. Over time, though, I think it tends to even out, as people see you really care about documentation and talking about how to use a project, and eventually people realize it's a real project and will start contributing and helping out. There's not a lot of easy answers, unfortunately.
