### ISSUE TITLE
Github Abandoned Account

### ISSUE THREAD

**Issue by flavioribeiro** [holman/feedback#644]
Hello Zach,

I think I should probably open a ticket on Github support but I'm wondering if you could have some kind of advice on it. We have a media player called [clappr](http://github.com/globocom/clappr) that's gaining traction and some [plugins](https://github.com/search?utf8=%E2%9C%93&q=clappr) are being created with clappr prefix. Our fist plan was to create an organization in order to keep all the efforts below the same umbrella, but it seems that's an [abandoned account](http://github.com/clappr) in there. 

We can surely add a suffix like clappr-player but do you think that it's possible to gh people give us owner's mail in order to convince him to hand over the name to us?

**Comment by holman** [comment]
You can ping support@github.com and ask; we'll usually give the username if they've been completely dormant for more than a year. We can't give out user contact information, though.
