### ISSUE TITLE
(feature request) In file view: see issues, pull requests, etc that are referencing the viewed file 

### ISSUE THREAD

**Issue by mindrones** [holman/feedback#645]
When viewing a file on a repository, I'd like to see if there are issues, pull requests, wiki pages, etc that reference the file.

For example, given a homebrew formula ([example](https://github.com/Homebrew/homebrew/blob/master/Library/Formula/a2ps.rb)):
- I'd like to see pull requests that modify the file I'm viewing (if any), so that I can see if someone is already suggesting modifications that I might start working on, or to chat in those pull requests conversations;
- I'd like to see issues referencing the file (if any), to avoid reporting a duplicate issue;
- I'd like to know if there are wiki pages that explicitly refer to this file (if any), to read more about it.

It would be nice to have a new column of buttons on the right (issues, wiki, etc) with the same functionality as the current ones, but related to the file instead of the whole repo.

**Comment by holman** [comment]
You'll want to shoot this to support@github.com as well; that'll get it in the system, so to speak.

**Comment by mindrones** [comment]
OK thanks!
