### ISSUE TITLE
About locating anywhere

### ISSUE THREAD

**Issue by greennyreborn** [holman/feedback#647]
I know there are some locating-anywhere jobs in github.
I wonder does it actually mean anywhere around the world?
I mean do you hire a lot of foreigners. Will the time differenct be a problem?

**Comment by holman** [comment]
Yup! Anywhere. We have people all over the world right now, and the company itself is 60% remote to San Francisco.

We work within timezones as part of [how we work](http://zachholman.com/posts/how-github-works-asynchronous/), so yeah, we're pretty good at it.

**Comment by mexisme** [comment]
I've been led to believe some countries might not be an option — excluding those with legal exclusions due to US legislation or Government position.
Is there any information about how this works, for GitHub?
