### ISSUE TITLE
Files modified but not in the commit list

### ISSUE THREAD

**Issue by sharat** [holman/feedback#648]
I have observed an interesting issues with one of our repos.

We have added an action to update database table in a commit. But somehow it disappeared in a future commit. The content within the code was disappeared but the file is not listed under modified file list. But the file is looks fine in the previous commit.

What could be some of the reasons for a strange scenarios like this? The developers are running Git 1.9.1 (Ubuntu)

**Comment by holman** [comment]
Not sure. Might want to look in the reflog, or shoot a message to support@github.com and they can look into it.
