### ISSUE TITLE
How might I score 30 minutes of your time for an interview?

### ISSUE THREAD

**Issue by jcutrell** [holman/feedback#649]
Pretty simple question. You're a busy guy.

I'd love to have you on Developer Tea. Is that a possibility in the coming weeks or months?

**Comment by holman** [comment]
Yeah! Caught your last episode or two.

Would be into it. Shoot me an email at zach at zachholman.com and we'll figure out the logistics.

:+1:

**Comment by jcutrell** [comment]
Hey Zach! Just wanted to double-check on this with you, sent you a couple of follow-ups since our last interaction.
