### ISSUE TITLE
Did you use Jekyll for your website?

### ISSUE THREAD

**Issue by stefania11** [holman/feedback#653]
If so wondering how you customized the theme :) 

thank you!

**Comment by holman** [comment]
Yup! I use Jekyll.

Just customized it. Here's the old version of my design that you can take a look at: https://github.com/holman/left

**Comment by stefania11** [comment]
Yes, I checked that. Do you have a link to new version?


Stefania Druga - Founder

+1 415 503 89 44

-----------------------------------------------------------------------------


HacKIDemia: Inspire the kids to imagine a better tomorrow

and give them the tools to build it!



Web <http://www.hackidemia.com/>| Facebook
<https://www.facebook.com/Hackidemia>| Twitter
<https://twitter.com/HacKidemia>| YouTube
<http://www.youtube.com/user/HacKIDemia>| Newsletter <http://bit.ly/ZrvxtF>|

**Comment by holman** [comment]
It's not open source.

**Comment by ultinomics** [comment]
For those of us new to Jekyll and aspiring to build pretty websites, any advice for learning to build websites such as yours? I know your website is not open source, which removes the "learn by example and copying" method. There must exist an optimal way to learn the nuts and bolts of Jekyll when learning via source code is no longer an option.

Your input would be greatly appreciated! Thanks.

**Comment by holman** [comment]
"learn by example and copying" is still how I recommend it. :) Take a peek at [holman/left](https://github.com/holman/left), fork it, and start modifying it for your own purposes from there. That's how I've learned Jekyll over the years.

[The Jekyll docs](http://jekyllrb.com) are also really great, too.

There's a possibility I might twerk and update my blog layout coming up soon, and if that happens I'll open source the current layout. We'll see if that ends up happening at all.

**Comment by ultinomics** [comment]
I'll keep an eye out! If I notice any sweeping changes, I'll politely pester you for the source code.

Currently learning using your /left template and mmistakes/minimal-mistakes

Thanks man!

**Comment by tejasmanohar** [comment]
@holman What's the intent behind not open-sourcing the site? To get the markup, people can view source and do the templating themselves anyways.

**Comment by holman** [comment]
I don't want too many clones at the moment. Once I've moved onto whatever layout I do next, then I don't mind open sourcing it and allowing people to use the theme.
