### ISSUE TITLE
Feedback culture at GitHub

### ISSUE THREAD

**Issue by freenerd** [holman/feedback#654]
Hi @holman,

I've been thinking about employee feedback culture recently. About a year ago @defunkt wrote [this blog post](https://github.com/blog/1843-diversity-and-feedback-at-github) where it reads:

> We are currently in the process of developing and implementing a formal, documented feedback system for everyone in the company. 

How did this play out? What's the system?

Kthxbye,
Johan

**Comment by holman** [comment]
We do personnel reviews with your manager every 6 months, which encompasses feedback from your manager and people you work with.
