### ISSUE TITLE
Easiest Way to Receive Webhooks

### ISSUE THREAD

**Issue by wadewilliams** [holman/feedback#655]
Hey @holman 

 I was googling around to figure out the absolute barebonesest minimal way to receive webhooks. I didn't find anything super interesting, since there's at least a million ways to do this. I'm much more interested in the implementation details of what to do with what's received than managing any real configuration for the server setup to accept POST requests and handle some JSON. 

 I figured you'd have 2¢ 

Thanks!

**Comment by holman** [comment]
Don't know! You could talk to GitHub, if you'd like. They'd probably have some thoughts. :)

**Comment by djch** [comment]
> Don't know! You could talk to GitHub, if you'd like. They'd probably have some thoughts. :)

:(

**Comment by wadewilliams** [comment]
@djch [This ought to do it](https://github.com/wadewilliams/webhook-receiver)
