### ISSUE TITLE
Has GitHub observed a sha1 collision?

### ISSUE THREAD

**Issue by kevinwallace** [holman/feedback#659]
Y'all process a lot of shas every day, and if someone was searching for a git object sha collision and managed to find one, it's not unlikely that they'd try pushing the colliding objects to GitHub.

Would you notice if such a thing happened?  Have you seen such a thing happen?

**Comment by kevinwallace** [comment]
Oh, wow, just saw https://twitter.com/holman/status/568874334233587712.  I don't know if that changes whether you can / want to answer these questions anymore -- feel free to disregard if so.

**Comment by holman** [comment]
We haven't seen any in practice yet, but we also weren't actively searching, either.

[It's pretty wildly unlikely, though](http://git-scm.com/book/en/v1/Git-Tools-Revision-Selection#A-SHORT-NOTE-ABOUT-SHA-1):

> Here’s an example to give you an idea of what it would take to get a SHA-1 collision. If all 6.5 billion humans on Earth were programming, and every second, each one was producing code that was the equivalent of the entire Linux kernel history (1 million Git objects) and pushing it into one enormous Git repository, it would take 5 years until that repository contained enough objects to have a 50% probability of a single SHA-1 object collision. A higher probability exists that every member of your programming team will be attacked and killed by wolves in unrelated incidents on the same night.

**Comment by matiasw** [comment]
https://shattered.it it's been made to happen now, on purpose.

**Comment by jamesalton** [comment]
"Too bad" that git files are "salted" with _blob (filesize)\0CONTENT_.
No git hash collision with Google's fun little experiment.

http://stackoverflow.com/questions/460297/git-finding-the-sha1-of-an-individual-file-in-the-index#answer-24283352
