### ISSUE TITLE
Why code?

### ISSUE THREAD

**Issue by yourmotherhatesme** [holman/feedback#663]
Why code at this point? Why not just roll in riches and troll around all day?

**Comment by holman** [comment]
Would love to, just as soon as I have any riches.

![17kdjxvdqvygyjpg](https://cloud.githubusercontent.com/assets/2723/6444462/966bd218-c0b2-11e4-8c1a-1d5ac010087b.jpg)

**Comment by Dreighen** [comment]
haha, I have a Scrooge McDuck picture like this as my metric for success. I tell myself the day I can swim in my money is the day I arrived lol.
