### ISSUE TITLE
Max salary GitHub

### ISSUE THREAD

**Issue by yourmotherhatesme** [holman/feedback#664]
What's the maximum salary you've seen w/ an engineer at GitHub?

**Comment by holman** [comment]
Not sure! That doesn't really get discussed much.

**Comment by Haglerd** [comment]
So are there even raises or do you just get a base pay and keep that forever?

**Comment by sharat** [comment]
@yourmotherhatesme Seems Glassdoor can help you 👍  - https://www.glassdoor.co.in/Salary/GitHub-Salaries-E671945.htm
