### ISSUE TITLE
Versioning for GitHub

### ISSUE THREAD

**Issue by hahmed** [holman/feedback#666]
Did you guys use SemVer for the main github.com app?

Versioning seems a little bit complicated for web applications, GitHub's major version must be a very big number if you do follow the SemVer conventions (bump major version for breaking changes).

Do you think SemVer works well for the github.com site? How do you know when you merged some changes which version (major, minor) to bump?

Thanks

**Comment by holman** [comment]
I'm not at GitHub anymore, but we never versioned the main app because it wasn't a dependency anywhere. Everything else was versioned for it, not the other way around.
