### ISSUE TITLE
Any book recommendations about similar organizational structure?

### ISSUE THREAD

**Issue by ScrimpyCat** [holman/feedback#669]
I'm going to be writing an essay for my management class in the upcoming weeks, and luckily enough I'll be able to write a bit about the style that is of interest to me (flatter organizational structures as opposed to hierarchical ones, open allocation, etc.). And so I've just been compiling up a list of relevant readings, some I've read before and some new ones that I haven't. And was wondering if you had any recommendations for books that discuss similar managerial philosophies to the ones you guys use at GitHub. Or any that have had an influence. 

Thanks :)

**Comment by wadewilliams** [comment]
If you haven't read [Michael O. Church's Open Allocation Rant](https://michaelochurch.wordpress.com/2012/09/03/tech-companies-open-allocation-is-your-only-real-option/), that's probably a good starting point.

**Comment by holman** [comment]
> And was wondering if you had any recommendations for books that discuss similar managerial philosophies

My main favorite was [REWORK](http://37signals.com/rework/)- that had a lot of influence on my line of thinking about remote, direction, and so on.

> to the ones you guys use at GitHub

I'm not at GitHub anymore. :) But GitHub's changed so dramatically that pretty much any business management book on hierarchy and managers would give you an idea of how to build that type of company.
