### ISSUE TITLE
Few Things I've Been Wondering

### ISSUE THREAD

**Issue by jwood803** [holman/feedback#670]
Been watching a lot of your talks and looking at blog posts and a few things popped into mind.

- As far as you know, is GitHub still using Campfire for their chats?
- Would you definitely recommend Keynote for presentation slides?
- Do you plan on still speaking as much as you did?

And I'm loving `boom`! Thanks!

**Comment by holman** [comment]
> As far as you know, is GitHub still using Campfire for their chats?

Yup!

> Would you definitely recommend Keynote for presentation slides?

Yup! I have a low opinion of web-based presentation software.

> Do you plan on still speaking as much as you did?

I hope so. Part of the problems I had the last year or so at GitHub was that I stopped learning new things, which became frustrating when it came to speaking at conferences. The future's already starting to look pretty awesome at getting something new inbound that I can finally have interesting things to talk about once again.

**Comment by jwood803** [comment]
> Yup! I have a low opinion of web-based presentation software.

After seeing yours I started wondering the same thing. I think I may switch!

> Part of the problems I had the last year or so at GitHub was that I stopped learning new things, which became frustrating when it came to speaking at conferences.

That sucks. I hope you continue because you really do give great presentations. I'll say now that if I'm at a talk that you give I will definitely, at least, get one beer for ya. :}

**Comment by salahanas** [comment]
THANKS
