### ISSUE TITLE
HOW DOES GITHUB WORK

### ISSUE THREAD

**Issue by deadindenver** [holman/feedback#675]
I WANT TO POST SOME COMMENTS FOR A GUY TO ASK HIM A QUESTION CANT FIGURE OUT HOW

**Comment by holman** [comment]
shhhhh lower your voice please

**Comment by deadindenver** [comment]
nice, so is this like a private message now? i really like the idea of github, i just wish i was a coder now

**Comment by holman** [comment]
This is an issue on my personal project, so the entire internet can see this. :)

Being a coder, like all things, comes with time. Just takes a lotta practice!

**Comment by deadindenver** [comment]
:)
