### ISSUE TITLE
Can I use a github pages site as my profile URL?

### ISSUE THREAD

**Issue by underscorejho** [holman/feedback#680]
When I try entering underscorejho.github.io/ as the url, it gives me
`please enter a url`
same for underscorejho.github.io/html/ and underscorejho.github.io/html/index.html
Is this not allowed for some reason?

**Comment by holman** [comment]
Not sure! I'd ping support@github.com about it.

**Comment by underscorejho** [comment]
Well, after some refreshing and what-not the problem seemed to fix itself. So for future reference, you can use a github pages site as a profile URL! At least now I know about this sweet repo.
