### ISSUE TITLE
Why does the mobile version of GitHub not allow to sort issues, pull requests etc.?

### ISSUE THREAD

**Issue by wp9015362** [holman/feedback#684]
Hello,

the desktop version of GitHub allows to sort issues, pull requests etc. by:

* Newest
* Oldest
* Most commented
* Least commented
* Recently updated
* Least recently updated

But the mobile version:

https://github.com/blog/1559-github-s-on-your-phone

apparently does not seem to have such a feature.

Why not?

And is there any chance you could add it?

Browsing issues on the mobile version really sucks due to that feature being absent.

So, it would be much appreciated if you could add it.

Regards

**Comment by holman** [comment]
Smaller screens means more focus and less time for features you'll use less often.

You might want to forward this on to support@github.com; they'll be able to tell GitHub's thoughts on it.
