### ISSUE TITLE
Why do you get so many general GitHub support / bugs / feature requests in this forum? eom

### ISSUE THREAD

**Issue by queuebit** [holman/feedback#686]
Why do you get so many general GitHub support / bugs / feature requests in this forum?

**Comment by holman** [comment]
I was there for a long, long time, and I think a lot of people associate me as their point of contact with GitHub. I'm happy to chat philosophy behind some of the stuff in the past here, but yeah, a lot of the support requests should be sent to support@github.com, obviously. :) I assume there'll still be those coming in over the next year or so... cost of doing what I did at that company for so long. It happens.
