### ISSUE TITLE
GitHub Issue/PullRequest "Liking"

### ISSUE THREAD

**Issue by SchumacherFM** [holman/feedback#692]
Hey Zach,

is there an ETA for that feature to Like/Unlike or +1/-1 an issue/pull request?

Thanks for an answer!

Cyrill

**Comment by holman** [comment]
I don't work on it anymore, but I doubt it. Adding a like/+1 button doesn't magically get everyone to stop replying `+1` in the issue.

**Comment by FagnerMartinsBrack** [comment]
> Adding a like/+1 button doesn't magically get everyone to stop replying +1 in the issue.

The greatest value would be to highlight the sum of "+1"s in a given issue or PR, gitlab does something similar by parsing how many "+1" comments exist in the issue/PR:

![image](https://cloud.githubusercontent.com/assets/835857/8561212/40f681e8-24f8-11e5-95a9-2429b6fcce3d.png)
