### ISSUE TITLE
Scaling Chat

### ISSUE THREAD

**Issue by wadewilliams** [holman/feedback#693]
FWIW, I think you should blog this one!

![holman_s_law_-_twitter_search](https://cloud.githubusercontent.com/assets/1676891/8101379/7a2992a8-0fcb-11e5-90c5-9ad756e20529.png)

![jeff_atwood___codinghorror____twitter](https://cloud.githubusercontent.com/assets/1676891/8101394/a001114a-0fcb-11e5-885e-8d1f1133f306.png)

So how does that scale? 

Our org adopted slack in beta -- we had a very limited deployment of Campfire before slack came out. Within a few days everyone in the org had Slack, but it quickly spiraled out of control. Add more slack rooms; sure, but, how can we make this work in the real world with teams that aren't bleeding edge?

Gen X'ers seem like they have a harder time wrapping their head around the opt-in/invite mentality of creating more rooms. And then there's 

![brandon_keepers___bkeepers____twitter](https://cloud.githubusercontent.com/assets/1676891/8101449/1e0250cc-0fcc-11e5-901d-da7acaf12fe7.png)

Which seems like a constant strife. E-Mail? Twitter? Slack? GitHub? Other web-based tools like Trello or other project management software? 

There's no clear way to normalize all the things. 

To be clear, I generally agree with "Holman's Law" as we're putting it on twitter, that another channel in slack will help you solve these problems with the team that needs to be there; but there's an adoption issue (for starters, with the Gen X'ers that aren't understanding "fast food social media" if you will)... and, at scale with 100s of employees as Atwood points out, there may be a limit to where this stops working.

Anyways mostly looking for some elaboration on the tweet :) Hope you're doing well!

![paulg_-_twitter_search](https://cloud.githubusercontent.com/assets/1676891/8101596/758291c6-0fcd-11e5-8a79-d0c34f73ae08.png)

**Comment by holman** [comment]
Specifically with regard towards chat, I do think adding more rooms tends to fix things. If a room becomes too noisy and the signal gets lost, the best way to recoup that is to split the room into smaller, more distinct subject areas, where possible.

> There's no clear way to normalize all the things.

I wouldn't worry about it too much. Certain things make sense in different areas — maybe documentation on GitHub, async chat in Slack, announcements via email... and it doesn't make sense to try to consolidate it into one particular medium.

In general, I wouldn't put too much faith into what I tweet, though.

**Comment by wadewilliams** [comment]
I guess the challenge is working with folks that think that it needs to be consolidated in order to communicate well ¯\_(ツ)_/¯

**Comment by andycox** [comment]
Even in larger organizations, most day-to-day collaboration is done in smaller groups, so I'm not as concerned about the scalability of Slack (assuming sensible use of channels) for asynchronous work. I think [this post](http://zachholman.com/posts/github-communication/) describes a good balance of different communication tools.
