### ISSUE TITLE
Deployment merge-base/merge questions

### ISSUE THREAD

**Issue by randy-girard** [holman/feedback#695]
I have read on various blog posts/issues two specific actions you guys run during your deployment process, and was wondering if you could share a little bit more information about them:

1. git merge base - One of the safe guards used, I was curious what you actually run and how you are analyzing the result to determine if its safe to continue. What would I do with the SHA at this point to determine safety? Is it just a simple:
```
git checkout branch
git merge-base HEAD master
##SHA##
```
2. The second is when a branch needs an auto merge from master during deployment. I assume the merge only happens on the server and is not actually pushed back to the repo. Also, if there is a merge conflict during this, does deploy stop (I assume). Is this a simple:
```
git merge --no-ff master
```

Thanks!

**Comment by holman** [comment]
Not sure what they end up doing these days. You can probably ping them at support@github.com and they might be able to shed some light on it.
