### ISSUE TITLE
Github GUI does not respond when scroll the branches using mouse wheel

### ISSUE THREAD

**Issue by saurabh-agnisys** [holman/feedback#700]
Github Supoort,
When I scroll my branches in a repository by using mouse wheel, GitHub does not respond and I need to close it forcefully and restart again. 

Please fix it ASAP.

Regards,
Saurabh Singh
Software Engineer,
Agnisys

**Comment by tarebyte** [comment]
@saurabh-agnisys you should email support@github.com instead.

**Comment by saurabh-agnisys** [comment]
Thanks tarebyte.
