### ISSUE TITLE
Which stack do you think is more promising in the futur, Ruby, Javascript or Swift ... or sth else ?  

### ISSUE THREAD

**Issue by Zianwar** [holman/feedback#701]
Hi Zach, 

Thanks again for oppeing this AMA, I just wanted to know your thoughts on this, as I started developing I begin with basic PHP and MySQL, that time, I thought that I finally made it and became a web developer, but once I discovered the world of Javascript and Nodejs I just felt suprised, then I read a little about Swift programming language and knowing the popularity it has gained I just couldn't choose between those, I think this is a common problem for all of us developers, we WANT TO LEARN THEM ALL!  

so what stack do you prefer and which one you think will be the futur ?

**Comment by tunnckoCore** [comment]
I categorically can say Javascript/nodejs.

**Comment by saadel** [comment]
+1

**Comment by holman** [comment]
I think my [last comment in this thread](https://github.com/holman/feedback/issues/698#issuecomment-118958873) covers this pretty well — basically I think everything is going to be fairly split for a little bit yet, and I don't see a big hegemony coming any time soon.
