### ISSUE TITLE
Github for Linux

### ISSUE THREAD

**Issue by nickedes** [holman/feedback#702]
Can we have a Github gui for Linux similar to the one for [windows](https://windows.github.com/) ?

**Comment by holman** [comment]
Sure!

**Comment by sharat** [comment]
People working at both GitHub and Atlassian are not so interested in Linux it seems.

**Comment by cirosantilli** [comment]
linuxers can use cli and vim :-)

**Comment by sharat** [comment]
btw, I found there are good amount of Git UI tools for Linux, but not really intuitive as SourceTree or GitHub for Mac/Windows.

See the list - https://git-scm.com/download/gui/linux

Git Cola - http://git-cola.github.io/
GitEye - http://www.collab.net/products/giteye
gitg - https://wiki.gnome.org/Apps/Gitg/
giggle - https://wiki.gnome.org/Apps/giggle/
