### ISSUE TITLE
What is your favourite movie?

### ISSUE THREAD

**Issue by HugoGiraudel** [holman/feedback#704]
The one you could watch over and over again. :)

**Comment by HugoGiraudel** [comment]
Daaaamn, not the AMA repo. :(

**Comment by HugoGiraudel** [comment]
Actually, it seems to be. I was confused by the name of the repo. Let's reopen!

**Comment by holman** [comment]
![strangelove-39094](https://cloud.githubusercontent.com/assets/2723/8767289/9bad05a4-2e0c-11e5-9495-d7eeb70ec59a.gif)

Absolutely *Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb*.

**Comment by djch** [comment]
When ever I see an _IF WE DON'T, REMEMBER ME_ gif posted anywhere I feel like I need to give a shout out to the source: http://iwdrm.tumblr.com/ 

Not sure _who_ exactly makes them, but they're amazing.
