### ISSUE TITLE
Is there a way to install GHE on RHEL6

### ISSUE THREAD

**Issue by xoco70** [holman/feedback#853]
Hi, 

I'm applying to a GitHub Solution Engineer position, and one question is: 

> We’re evaluating GitHub Enterprise but we’re not interested in running a virtual appliance. Is there a way to manually install the software package on RHEL6? We have hundreds of developers who want to use GitHub but our security team won’t sign off on GitHub unless you can offer a bare metal install.

Based on the [docs](https://enterprise.github.com/faq#faq-5), RHEL6 is not a supported platform, and it is not possible to install it manually on bare metal.

Is there a workaround to achieve it ???

**Comment by xoco70** [comment]
It seems that a collegue that is using GH has asked the support, and I will get the response on monday, so I prefer asking you another question :)

**Comment by aaugusthy** [comment]
@xoco70, did you ever get the answer to this question that you posted last year?

Any guidance on if there is a workaround or a viable solution would be greatly appreciated!

Thanks
