### ISSUE TITLE
What's up with the "Need help with the holman/ama project?" banner?

### ISSUE THREAD

**Issue by orf** [holman/feedback#857]
When submitting an issue to Github support there is a prominent banner displayed linking to this repo:

<img width="1282" alt="Screenshot 2019-05-28 at 19 34 04" src="https://user-images.githubusercontent.com/1027207/58503026-a9bbd600-817f-11e9-8a68-8a286bacf1bb.png">

And one when you're writing:

<img width="649" alt="Screenshot 2019-05-28 at 19 37 08" src="https://user-images.githubusercontent.com/1027207/58503167-00c1ab00-8180-11e9-9d19-0f433e7dfe43.png">

I don't get it. I've never heard of this AMA before, are there really such a significant number of people putting AMA questions for you in Github support that warrants such a large banner?

**Comment by holman** [comment]
Support just shows the last repo you were looking at, so you just have landed on this repo at some point.
