### ISSUE TITLE
What is your favorite domain name registrar?

### ISSUE THREAD

**Issue by ghost** [holman/feedback#858]
What is your favorite domain name registrar?

**Comment by holman** [comment]
On Hover these days, but I think all registrars are kinda crap.

**Comment by suhailvs** [comment]
whois.com is pretty good.

**Comment by holman** [comment]
I’ve since switched most domains to CloudFlare and been pretty happy with it. 🎊

**Comment by suhailvs** [comment]
@holman  you can't purchase new domain names in cloudflare. only transfering.
