### ISSUE TITLE
GitLab vs GitHub?

### ISSUE THREAD

**Issue by ghost** [holman/feedback#859]
**GitLab vs GitHub?**

Do you like GitHub/GitLab and please elaborate it!

Thanks!

**Comment by holman** [comment]
Haha, that's a tricky one. I'm a fan of all three, really: I think GitHub, GitLab, and Atlassian are all doing really cool stuff right now. Good time to be a developer.

I'm probably not a super great person to ask- I have friends at all three companies, I'm financially invested in all three companies, and I generally think all their products are pretty damn good these days. GitHub is starting to catch up to GitLab's product offerings, GitLab is continuing to build some really innovative shit, Atlassian has incredible inertia as a behemoth and is somehow still increasing speed, and all three keep on making hella money, which I think is great. Huge change from ten years ago in the industry.

Anyway, I think they're all good stuff. If you're totally a neutral, I'd say go with GitLab, but really you'll probably be fine with any of them. (And all of them! It's totally legal to use more than one, and I think that's probably a better approach for us all to take as an industry, really).
