### ISSUE TITLE
Technologies du jour

### ISSUE THREAD

**Issue by jsimpson** [holman/feedback#862]
What sorts of technologies do you see dominating the coming decade? What sorts of trends do you think will go on with languages? Forgive me for assuming, but it strikes me that Ruby is close to both of our hearts... What do you perceive as it's place in the coming years?

**Comment by holman** [comment]
I think JavaScript is the boring answer but the most correct one. It’s just got so much inertia, and it’s quickly just becoming the lingua franca for everything. Especially with React coming on so strongly, I think it’s just the right answer.

That said, the JavaScript ecosystem is totally fucked right now, but eventually that’ll get sorted out.
