### ISSUE TITLE
How to get a business logic OSS project off the ground

### ISSUE THREAD

**Issue by behoyh** [holman/feedback#863]
Hey Zach,

I’ve got this app that I think a lot of founders and developers in general can use as a component in their projects. The problem is, it doesn’t solve a technical issue, but a common business one.

Is this normal for an OSS project? How should I approach building and developing this?

[Repo in question](https://github.com/behoyh/invert-api)

**Comment by behoyh** [comment]
Thanks in advance!

-Beshoy Hanna

**Comment by holman** [comment]
Sure, it could be.

I think compared to, a CLI, for example, or a library, there's a lot more code to look at, to install, to upkeep, etc. So you have to convince people a lot more than other projects. I think if you're going to do it right you'd need to build a website, documentation, screenshots screenshots screenshots, etc. You basically need to work a lot harder to explain why someone might need it.

**Comment by behoyh** [comment]
Thank you! I will start the website once the UI component is completed!
