### ISSUE TITLE
Auth server

### ISSUE THREAD

**Issue by MatteoGauthier** [holman/feedback#868]
What's the best way to authantificate a user to his <service> account and get some data from this <service> ?
Example :
Auth on my app with spotify and get your music stats.

What's the best hosting way for the auth server ? Can i "serverless" my app ?

**Comment by holman** [comment]
Plenty of options. You could either roll it yourself (involving serverless functions at various vendors), or use something like Auth0. If you want to connect with a third party, though, you’d probably want to roll your own.
