### ISSUE TITLE
Do you know where github hosted now?

### ISSUE THREAD

**Issue by xTunqki** [holman/feedback#871]
Github down a few days ago like 1 hour, i know you're not working at github anymore but i don't know who to ask, so do you know where does github hosted now? I mean how something big like Github could down for 1 hour

**Comment by holman** [comment]
Nope.

**Comment by sharat** [comment]
@xTunqki Not sure if they moved elsewhere, and the current state of MetalCloud. However their static files returns [AWS IP ranges](https://ip-ranges.amazonaws.com/ip-ranges.json)

**Comment by ferhatelmas** [comment]
probably in the process of moving to azure.
