### ISSUE TITLE
Is github going to implement an "issue recommendation" feature? It will help me find new work to do and be more productive.

### ISSUE THREAD

**Issue by DGKSK8LIFE** [holman/feedback#874]

**Comment by holman** [comment]
No idea what they’re doing these days.

**Comment by DGKSK8LIFE** [comment]
> No idea what they’re doing these days.

ty. Anyone I can ask/is there somewhere where I can request features to be added to github?

**Comment by holman** [comment]
support@github.com

**Comment by DGKSK8LIFE** [comment]
ty @holman. Good luck on future endeavors!
