### ISSUE TITLE
What does the eye with a slash icon on my organization mean?

### ISSUE THREAD

**Issue by pblanton** [holman/feedback#876]
I recently created a new organization and created a new repo in it. The organization is available while not logged in, so it seems to be properly configured to be public, though the organization doesn't yet show up in the Github search.

When looking at my profile, I see two organizations in it, but the new one "Gort Technology" has an eye with a slash over it...

![image](https://user-images.githubusercontent.com/1143649/95907310-900d3580-0d58-11eb-85c3-5c54ccda4a98.png)

What does that mean?
And when should I expect my organization to show up in Github searches?

**Comment by holman** [comment]
No idea, tbh. Haven’t seen it before.

**Comment by austinbutler** [comment]
https://github.com/refined-github/refined-github

**Comment by bmndc** [comment]
Sorry to comment on a long closed issue and ping everyone, I was having the same issue and found this as the first result on Google. For future references — the slashed eye icon means the organisation won't be shown on your public profile, i.e. when people see your profile they won't know you joined that organisation. To change that, go to the People tab of your org, and change your organisation visibility from Private to Public.

![Screenshot of the Organisation visibility menu, with two options for Public and Private](https://github.com/user-attachments/assets/f7e5a593-4e96-42f6-9c3b-69e18187f562)
