### ISSUE TITLE
Broken image breaks layout

### ISSUE THREAD

**Issue by theabbie** [holman/feedback#877]
https://github.com/WaylonWalker/WaylonWalker

This specific Repository is an example, but the problem exists if a wide image has broken URL, it breaks the page layout on mobile website. I have attached the screenshot for reference. It should be fixed.

*P.S. I have contacted GitHub support, the support@github.com no longer works, this is a generic bug, so, this place seems suitable.*

Thank you,

![Screenshot_20201106-123814_Chrome](https://user-images.githubusercontent.com/17960677/98337386-8e205480-202e-11eb-840e-580c05faf754.png)

**Comment by holman** [comment]
Haven’t worked there in ages, sorry.

**Comment by theabbie** [comment]
@holman Could you atleast tell me a correct place to report this, that support email doesn't work.

**Comment by holman** [comment]
Prolly a support link on the site somewhere.
