### ISSUE TITLE
What is the biggest open-source part of GitHub?

### ISSUE THREAD

**Issue by stampylongr** [holman/feedback#878]
As in a project created by GitHub, used by GitHub internally, and have open-sourced it.

Asking for a friend.

**Comment by holman** [comment]
Not really sure. I guess if you [search for it](https://github.com/search?o=desc&q=org%3Agithub&s=stars&type=Repositories) it’d be github/gitignore or github/fetch. There’s probably some other projects, though, and you could maybe argue libgit2 as well.
