### ISSUE TITLE
What was Halp?

### ISSUE THREAD

**Issue by lunaisnotaboy** [holman/feedback#892]
Hi-

I was just going through a bunch of your old presentations on [Speaker Deck](https://speakerdeck.com/holman) (really good, BTW!), and I noticed an app called [Halp](https://speakerdeck.com/holman/how-github-works?slide=91) is mentioned in one of the slides. I was wondering, is this the same Halp that is now under Atlassian's umbrella, or is it something else?

If so, was still in use at the time of your leaving? (And, this is more because I tend to like to look at all of the infrastructure surrounding GitHub, is the source code available, and if not, would I be able to see it? (dumb question, i know, sorry!!))

Sorry for all the questions! Hope you're having a great day. 🤗

**Comment by holman** [comment]
Halp was just our own brand of support tooling. It started with our first support staff being annoyed at having to do the same things over and over again, so he built a kind of shared set of scripts to automate a lot of the common responses. And then it just grew into a proper app over the years. It was really pretty killer (and yet another example of something GitHub should have spun off but instead killed it like most good ideas they had).

I think it lived into 2016, 2017, something like that, and now has been replaced with one of the many support desk software out there. Still hear Hubbers complain they can't use Halp to respond to tickets to this day, though.

**Comment by lunaisnotaboy** [comment]
Ah, okay, thanks!
