### ISSUE TITLE
> They show up when I'm logged in my own account, but not from other users' views. What special situation am I falling into? Thanks.

### ISSUE THREAD

**Issue by ramiz03** [holman/feedback#894]
> They show up when I'm logged in my own account, but not from other users' views. What special situation am I falling into? Thanks.

same tbh. I see other people who are part of the same organization has their organization listed in their public profile but doesn't work for me :(

P.S.: it's visible to me when i'm logged in and see my profile

do lmk if someone can figure out what's the issue

_Originally posted by @ramiz03 in https://github.com/holman/ama/issues/274#issuecomment-1521674075_

**Comment by amitjimiwal** [comment]
@ramiz03 You can follow these steps to do that:
 1. Go to your Organisation Page.
 2. Go to Peoples tab.
 3. Find Yourself in that and there is a dropdown which is by default private make it public & you are  gtg :)
