### ISSUE TITLE
What was the `Blakefile` in GitHub?

### ISSUE THREAD

**Issue by lunaisnotaboy** [holman/feedback#896]
I've seen it referenced a few times, and I can't find anything on it.

**Comment by holman** [comment]
Hah, just a file dropped into the root in honor of our friend @bmizerany.

**Comment by lunaisnotaboy** [comment]
Ah! Thanks for clarifying. Hope I didn't bring up bad memories :)

**Comment by holman** [comment]
haha, not at all. Blake is a legend.
